url: https://qidotslock.com

title: Qidots

keywords: 

description: 

company: Qidots Secuirty Technology Co.,Ltd (Foshan)

address: 3/F, Blok 2, No. 39 Shunxiang Rd, Fengxiang Industrial Zone, Daliang, Shunde District 528300, Foshan, Guangdong, China

tel1: +86-0757-22308132

tel2: +86-13715528361

fax: +86-0757-22308126

email1: sales@qidots.com

email2: sale05@qidots.com

exclude:
  - README.md
  - style.css
