url: https://qidotslock.com

title: Qidots

keywords: 

description: 

company: Qidots Secuirty Technology Co.,Ltd (Foshan)

address: 3/F, Blok 2, No. 39 Shunxiang Rd, Fengxiang Industrial Zone, Daliang, Shunde District 528300, Foshan, Guangdong, China

tel: +86-0757-22308132

fax: +86-0757-22308126

email: sales@qidots.com

exclude:
  - README.md
  - style.css
